# Generated by Django 5.1.15 on 2026-05-22 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('concert', '콘서트'), ('musical', '뮤지컬'), ('play', '연극'), ('sports', '스포츠'), ('etc', '기타')], default='concert', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/thumbnails/')),
            ],
            options={
                'db_table': 'event',
                'indexes': [models.Index(fields=['is_deleted', 'created_at'], name='event_deleted_created_idx'), models.Index(fields=['genre'], name='event_genre_idx'), models.Index(fields=['view_count'], name='event_view_count_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('event_date', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_times', to='events.event')),
            ],
            options={
                'db_table': 'event_time',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100)),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('price', models.PositiveIntegerField(default=0)),
                ('event_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='events.eventtime')),
            ],
            options={
                'db_table': 'zone',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('seat_number', models.CharField(max_length=20)),
                ('seat_status', models.CharField(choices=[('available', '예매가능'), ('booked', '예매됨'), ('reserved', '결제완료')], default='available', max_length=20)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.zone')),
            ],
            options={
                'db_table': 'seat',
            },
        ),
        migrations.AddIndex(
            model_name='eventtime',
            index=models.Index(fields=['event', 'event_date'], name='eventtime_event_date_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['event_time', 'rank'], name='zone_eventtime_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['zone', 'seat_status'], name='seat_zone_status_idx'),
        ),
    ]
