# Generated by Django 6.0.5 on 2026-05-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_reserve',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
