# Generated by Django 5.1.15 on 2026-05-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='face_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
